server:
  port: 8080

spring:
  datasource:
    url: ${DB_CONNECTION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  mail:
    username: smartwateringorg@gmail.com

jwt:
  signerKey: ${SIGNER_KEY}
  accessDuration: 3600
  refreshDuration: 360000

mqtt:
  broker: ${BROKER_URL}
  clientId: smart-watering
  username: ${BROKER_USERNAME}
  password: ${BROKER_PASSWORD}

sendgrid:
  api-key: ${SENDGRID_API_KEY}